### ISSUE TITLE
Consider a new movement: standing

### ISSUE THREAD

**Issue by Btimes2** [Sasszem/crossfire#193]
Please consider to include a new command when the player can stand completely still. It would be  useful sometimes, especially for the "ghost" powerup, as now it is hard to maximize its advantages. 

Maybe the player could stand still by clicking with the mouse, or pressing S (for "stand") on the keyboard.

**Comment by Sasszem** [comment]
I do not think standing would work out, but I plan to do a time-slowdown mode, that'd help
