### ISSUE TITLE
Optimize AI movements 2

### ISSUE THREAD

**Issue by Btimes2** [Sasszem/crossfire#195]
There was a time when the AI wanted to run from the buster player, but when it started, it faced towards a wall, so it run in a sharp angle, running very slowly because of the friction on the wall. A "smart" enemy would have  turned away from the wall first, and run in parallel with it.

**Update.** When an enemy gets into a corner now, its movement slows down so much that it is in fact stuck.

**Comment by Sasszem** [comment]
Done in #214
