### ISSUE TITLE
A level up system

### ISSUE THREAD

**Issue by Btimes2** [Sasszem/crossfire#209]
A possible enhancement and "gamification" would be implementing a level up system.
Tetris is game-like because it gets faster and faster every level.
This game maximizes the difficulty at about 300 points, which can be reached quite soon. After that moment, the number of enabled enemies cannot grow anymore (it reaches the ceiling), so the game will never be more difficult. 

A possible level-up system would be that the ceiling lifts up by one enemy at every 500 or 1000 points. So if the maximum number of big enemies is 3 at the beginning, and the max. num. of small enemies is 10, then after reaching this step, maybe 1000 points, then the maximum would increase by one: 4 and 11. Thus, at 10 000 scores, the possible number of enemies on the board would be 33 instead of the initial 13. 

Another option is to increase the speed (like in Tetris). The game would be more and more difficult to play. This would affect the player and the enemies (and the bullets) at the same time, so it could be achieved by implementing an internal "clock speed". The enemies could also fire more frequently. The enemies would get the same speed enhancement as the player, so they would level up equally, but an increased speed would still be an increase in difficulty for a human player.

**Comment by Btimes2** [comment]
Another idea: if the player reached a higher level, the score bubbles and droplets should disappear slightly sooner gradually. Of course, a minimum time should be set for them, to prevent the creation of an unbeatable level.

**Comment by Sasszem** [comment]
Hups, not done powerup despawn-time tweak...
