### ISSUE TITLE
Font recommendation

### ISSUE THREAD

**Issue by Btimes2** [Sasszem/crossfire#229]
There are several free or free for noncommercial fonts available to enhance the feeling. 
I collected a bunch of futuristic and game-like fonts for this project: 

Sci-fi fonts:
- https://www.1001fonts.com/xirod-font.html
- https://www.1001fonts.com/lunasol-font.html
- https://www.1001fonts.com/supercomputer-font.html
- https://www.1001fonts.com/mainframe-font.html
- https://www.1001fonts.com/lazenby-computer-font.html
- https://www.1001fonts.com/vectroid-font.html
- https://www.1001fonts.com/astron-boy-font.html

This font is also awesome, this is not that futuristic, it looks rather like a circuit:
- https://www.1001fonts.com/membra-font.html

**Comment by Sasszem** [comment]
Picked the [supercomputer font](https://www.1001fonts.com/supercomputer-font.html)
Thanks for the suggestion!

**Comment by Btimes2** [comment]
You are welcome :)
