### ISSUE TITLE
Buster player

### ISSUE THREAD

**Issue by Btimes2** [Sasszem/crossfire#230]
In release 0.96, the buster player may collide with the ghost player. I had a game in which the player became transparent like the ghost player, and bullets went throught it, but its size was small like the buster player. Maybe if I get 2 droplets at the same time, then they can get mixed up?

On Windows, the buster player's statusbar (showing the remaining time of this enhancement) once looked faulty. When it reached about 50%, it restarted from the right, and it measured the remaining 50% from the right edge. So when the enhancement runned out of time, the statusbar showed 50% instead of 0%. Version is still 0.96.

**Comment by Sasszem** [comment]
Please specify your Löve2D version for both platforms. I'll check this our myself, and also send you a rigged build that always gives you those powerups for testing.

**Comment by Btimes2** [comment]
I have 11.2 installed on Linux

**Comment by Sasszem** [comment]
I think I found the cause of the latter. Changing the powerup state does NOT stop the tweening of the countdown, and that causes funny effects. It's an easy fix tough.

**Comment by Sasszem** [comment]
Found the cause of the other as well. Powerup cleanup was not done properly.
